#!/bin/bash
#
# Setup various JavaScript stuff
#

# -----------------------------------------------------------------------------
# Setup nvm
#  https://github.com/creationix/nvm
#
source $HOME/.dotfiles/js/nvm

# -----------------------------------------------------------------------------
# Setup npm
#
if [[ -e $HOME/.npm ]]; then
  export MANPAT=$MANPATH:$HOME/.npm/man
fi

