#!/bin/bash
#
# Setup various JavaScript stuff
#

# -----------------------------------------------------------------------------
# Setup nvm
#  https://github.com/creationix/nvm
#
source $HOME/.dotfiles/js/nvm

