#!/bin/bash
# -----------------------------------------------------------------------------
# Setup RVM
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
# -----------------------------------------------------------------------------
# Tired of typing rspec spec
#
alias spec='/usr/bin/env rspec spec'

