#!/bin/bash
# -----------------------------------------------------------------------------
# Setup RVM
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
# -----------------------------------------------------------------------------
# Don't have to require rubygems always
#
export RUBYOPT=rubygems

