#!/bin/bash
#
# https://github.com/misham/dotfiles
#
# Based on stuff I found on dotfiles.org and github.com
#
# -----------------------------------------------------------------------------
# Uncompress a passed in file
#
# @param $1 File to uncompress
#
function extract {
  if [ -f "$1" ] ; then
    case $1 in
      *.tar.bz2)
      tar -xjvpf "$1"
      ;;
      *.tar.gz)
      tar -xzvpf "$1"
      ;;
      *.bz2)
      bunzip2 "$1"
      ;;
      *.rar)
      rar x "$1"
      ;;
      *.gz)
      gunzip "$1"
      ;;
      *.tar)
      tar -xvpf "$1"
      ;;
      *.tbz2)
      tar -xjvpf "$1"
      ;;
      *.tgz)
      tar xzf "$1"
      ;;
      *.zip)
      unzip "$1"
      ;;
      *.Z)
      uncompress "$1"
      ;;
      *.rpm)
      rpm2cpio "$1" | cpio -idmv
      ;;
      *.deb)
      ar p "$1" data.tar.gz | tar zx
      ;;
      *)
      echo "'$1' cannot be extracted via extract()"
      ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
} # extract
# -----------------------------------------------------------------------------
# Setup project environment
#
# @param Name of project, case sensitive
#
function project {
  if [[ -e "$HOME/$PROJECT_DIR/$1" && -d "$HOME/$PROJECT_DIR/$1" ]]; then
    cd "$HOME/$PROJECT_DIR/$1"
    if [[ -e .project.env ]]; then
      source .project.env
    fi

    if [[ -e "$HOME/$PROJECT_DIR/$1/bin" && -d "$HOME/$PROJECT_DIR/$1/bin" ]]; then
      export PATH=$HOME/$PROJECT_DIR/$1/bin:$PATH
    fi
  fi
}
