set nocompatible

" Set tabstop to 2 spaces, make spaces not tabs  -- swi:
set ts=2
set et

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set autoindent		" always set autoindenting on
set smartindent		" always set autoindenting on
set shiftwidth=2 

set showmode
set showmatch

set guioptions-=T

set number          " Show line numbers

set nowrap

set nobackup
set writebackup

set history=50		  " keep 50 lines of command line history
set ruler		        " show the cursor position all the time
set showcmd		      " display incomplete commands
set incsearch		    " do incremental searching

" Don't use Ex mode, use Q for formatting
map Q gq

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Set the colors
colorscheme evening
highlight StatusLine ctermfg=DarkBlue ctermbg=LightGray
highlight Search ctermfg=Blue ctermbg=LightGrey

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

endif " has("autocmd")

" Stop VIM from auto-inserting C++ '//' comments
set comments=sr:/*,mb:*,el:*/ 
set fo-=c fo-=r fo-=o
