#
# My zshrc - https://github.com/misham/dotfiles
#
DOTFILES=$HOME/.dotfiles
# -----------------------------------------------------------------------------
# oh-my-zsh setup
#
export ZSH="$HOME/.oh-my-zsh"

# Lazy-load NVM on first use. Keep installed Node versions under ~/.nvm while
# preferring the newer Homebrew-provided NVM script on macOS.
export NVM_DIR="$HOME/.nvm"
if [[ -s "/opt/homebrew/opt/nvm/nvm.sh" ]]; then
  NVM_SCRIPT="/opt/homebrew/opt/nvm/nvm.sh"
elif [[ -s "/usr/local/opt/nvm/nvm.sh" ]]; then
  NVM_SCRIPT="/usr/local/opt/nvm/nvm.sh"
elif [[ -s "$NVM_DIR/nvm.sh" ]]; then
  NVM_SCRIPT="$NVM_DIR/nvm.sh"
fi

if [[ -n "$NVM_SCRIPT" ]]; then
  _load_nvm() {
    local script="$NVM_SCRIPT"
    local completion

    unfunction nvm node npm npx pnpm pnpx yarn corepack 2>/dev/null
    source "$script"

    for completion in "$script:h/etc/bash_completion.d/nvm" "$NVM_DIR/bash_completion"; do
      if [[ -r "$completion" ]]; then
        autoload -Uz +X bashcompinit && bashcompinit
        ZSH_VERSION= source "$completion"
        break
      fi
    done

    unset NVM_SCRIPT
    unfunction _load_nvm
  }

  for command in nvm node npm npx pnpm pnpx yarn corepack; do
    eval "${command}() { _load_nvm; ${command} \"\$@\"; }"
  done
  unset command

  _find_nvmrc() {
    local dir="${PWD:A}"

    while [[ -n "$dir" ]]; do
      if [[ -f "$dir/.nvmrc" ]]; then
        print -r -- "$dir/.nvmrc"
        return 0
      fi
      [[ "$dir" == "/" ]] && break
      dir="${dir:h}"
    done

    return 1
  }

  _autoload_nvmrc() {
    local nvmrc_path="$(_find_nvmrc)"

    if [[ -n "$nvmrc_path" ]]; then
      [[ "$nvmrc_path" == "$NVM_AUTO_NVMRC" ]] && return
      (( $+functions[_load_nvm] )) && _load_nvm

      if [[ -z "$NVM_AUTO_NVMRC" ]]; then
        typeset -g NVM_AUTO_PREVIOUS_VERSION="$(nvm current)"
      fi

      if nvm use; then
        typeset -g NVM_AUTO_NVMRC="$nvmrc_path"
      fi
    elif [[ -n "$NVM_AUTO_NVMRC" ]]; then
      local previous_version="${NVM_AUTO_PREVIOUS_VERSION:-default}"

      if nvm use "$previous_version" || nvm use node; then
        unset NVM_AUTO_NVMRC NVM_AUTO_PREVIOUS_VERSION
      fi
    fi
  }
fi

# Lazy-load Conda on first use instead of generating and evaluating its shell
# hook during every login shell.
for conda_exe in \
  "/opt/homebrew/Caskroom/miniforge/base/bin/conda" \
  "/usr/local/Caskroom/miniforge/base/bin/conda" \
  "$HOME/miniforge3/bin/conda" \
  "$HOME/miniconda3/bin/conda" \
  "$HOME/anaconda3/bin/conda"; do
  if [[ -x "$conda_exe" ]]; then
    CONDA_LAZY_EXE="$conda_exe"
    break
  fi
done
unset conda_exe

if [[ -n "$CONDA_LAZY_EXE" ]]; then
  _load_conda() {
    local conda_exe="$CONDA_LAZY_EXE"
    local conda_setup

    unfunction conda 2>/dev/null
    if conda_setup="$("$conda_exe" shell.zsh hook 2>/dev/null)"; then
      eval "$conda_setup"
    else
      export PATH="${conda_exe:h}:$PATH"
      rehash
    fi

    unset CONDA_LAZY_EXE
    unfunction _load_conda
  }

  conda() {
    _load_conda
    conda "$@"
  }
fi

# Lazy-load RVM on the first Ruby command or when entering a Ruby project.
export rvm_path="$HOME/.rvm"
RVM_SCRIPT="$rvm_path/scripts/rvm"
if [[ -s "$RVM_SCRIPT" ]]; then
  _load_rvm() {
    local script="$RVM_SCRIPT"

    unfunction rvm ruby gem bundle bundler rake irb erb ri rdoc rails \
      ruby-lsp rubocop rspec rackup puma sidekiq spring 2>/dev/null
    source "$script"

    unset RVM_SCRIPT
    unfunction _load_rvm
  }

  for command in rvm ruby gem bundle bundler rake irb erb ri rdoc rails \
    ruby-lsp rubocop rspec rackup puma sidekiq spring; do
    eval "${command}() { _load_rvm; ${command} \"\$@\"; }"
  done
  unset command

  _find_rvm_project() {
    local dir="${PWD:A}"
    local marker

    while [[ -n "$dir" ]]; do
      for marker in .ruby-version .ruby-gemset .rvmrc; do
        # ~/.rvmrc is global RVM configuration, not a project marker.
        [[ "$dir" == "$HOME" && "$marker" == ".rvmrc" ]] && continue

        if [[ -f "$dir/$marker" ]]; then
          print -r -- "$dir/$marker"
          return 0
        fi
      done
      [[ "$dir" == "/" ]] && break
      dir="${dir:h}"
    done

    return 1
  }

  _autoload_rvm_project() {
    (( $+functions[_load_rvm] )) || return
    local project_marker="$(_find_rvm_project)"
    [[ -n "$project_marker" ]] || return

    _load_rvm
    rvm use
  }
fi

plugins=(
  # Shell UX
  vi-mode           # replaces set -o vi + bind
  history           # history aliases
  colored-man-pages # color in man pages
  extract           # replaces custom extract function

  # Git
  git               # gst, gco, gcmsg, gp, etc.

  # Ruby
  rvm               # proper RVM shell function loading
  rake              # rake task completion
  bundler           # be, bi, bu aliases
  gem               # gem completions

  # Node/JS
  npm               # npm aliases and completions; NVM is lazy-loaded above

  # Python
  pyenv             # pyenv init

  # Cloud/Infra
  aws               # AWS profile switching (asp) + completions
  docker            # docker completions
  docker-compose    # docker-compose completions

  # macOS
  macos             # ofd, pfd, ql, tab, showfiles/hidefiles

  # SSH
  ssh               # SSH host completions
)

source $ZSH/oh-my-zsh.sh

# Activate a project's .nvmrc on entry without loading NVM for other shells.
if (( $+functions[_autoload_nvmrc] )); then
  autoload -Uz add-zsh-hook
  add-zsh-hook chpwd _autoload_nvmrc
  _autoload_nvmrc
fi

# Load RVM when starting in or entering a Ruby project.
if (( $+functions[_autoload_rvm_project] )); then
  autoload -Uz add-zsh-hook
  add-zsh-hook chpwd _autoload_rvm_project
  _autoload_rvm_project
fi
# -----------------------------------------------------------------------------
# Get aliases
#
source $DOTFILES/shell/aliases
# -----------------------------------------------------------------------------
# Get functions
#
source $DOTFILES/shell/functions
# -----------------------------------------------------------------------------
# Setup completions
#
source $DOTFILES/zsh/completion
# -----------------------------------------------------------------------------
# History settings
#
export HISTSIZE=10000
export SAVEHIST=10000
setopt INC_APPEND_HISTORY   # replaces PROMPT_COMMAND='history -a'
setopt HIST_VERIFY           # replaces histverify
setopt HIST_IGNORE_ALL_DUPS  # replaces HISTCONTROL=ignoreboth
setopt HIST_IGNORE_SPACE     # replaces HISTCONTROL=ignorespace
# -----------------------------------------------------------------------------
# Shell options
#
setopt GLOB_DOTS     # replaces dotglob
setopt CDABLEVARS    # replaces cdable_vars
setopt EXTENDED_GLOB # replaces extglob
setopt NOTIFY        # replaces set -o notify
# -----------------------------------------------------------------------------
# Using VIM for editing
#
export EDITOR="vim"
# -----------------------------------------------------------------------------
# Make GPG play nice
#
export GPG_TTY=$(tty)
# -----------------------------------------------------------------------------
# Setup project stuff
#
export PROJECT_DIR="Projects"
# -----------------------------------------------------------------------------
# colored GCC warnings and errors
#
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# -----------------------------------------------------------------------------
# make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
# -----------------------------------------------------------------------------
# Better colors for less
#
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
# -----------------------------------------------------------------------------
# Setup any machine-specific configs
#
[[ -s "$HOME/.zshrc.local" ]] && . "$HOME/.zshrc.local"
# -----------------------------------------------------------------------------
# Setup starship
#
eval "$(starship init zsh)"
# -----------------------------------------------------------------------------
# Enable Claude LSP support
#
export ENABLE_LSP_TOOL=1
# -----------------------------------------------------------------------------
# Enable shell command completion for gcloud.
#
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then
  . "$HOME/google-cloud-sdk/completion.zsh.inc"
fi
# -----------------------------------------------------------------------------
# Setup AWS console
#
export AWS_PAGER=""

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/misham/.cache/lm-studio/bin"
# End of LM Studio CLI section

