#
# My zshrc - https://github.com/misham/dotfiles
#
DOTFILES=$HOME/.dotfiles
# -----------------------------------------------------------------------------
# OS Detection
#
_is_macos() { [[ "$(uname -s)" == "Darwin" ]]; }
_is_linux() { [[ "$(uname -s)" == "Linux" ]]; }
# -----------------------------------------------------------------------------
# oh-my-zsh setup
#
export ZSH="$HOME/.oh-my-zsh"

plugins=(
  # Shell UX
  vi-mode           # replaces set -o vi + bind
  sudo              # Esc+Esc prepends sudo
  history           # history aliases
  colored-man-pages # color in man pages
  extract           # replaces custom extract function

  # Git
  git               # gst, gco, gcmsg, gp, etc.

  # Ruby
  rvm               # proper RVM shell function loading
  rake              # rake task completion
  bundler           # be, bi, bu aliases
  gem               # gem completions

  # Node/JS
  nvm               # lazy-loads nvm
  npm               # npm completions

  # Python
  pyenv             # pyenv init

  # Cloud/Infra
  aws               # AWS profile switching (asp) + completions
  ansible           # ansible completions
  docker            # docker completions
  docker-compose    # docker-compose completions

  # macOS
  macos             # ofd, pfd, ql, tab, showfiles/hidefiles

  # SSH
  ssh               # SSH host completions
)

source $ZSH/oh-my-zsh.sh
# -----------------------------------------------------------------------------
# Get aliases
#
source $DOTFILES/shell/aliases
# -----------------------------------------------------------------------------
# Get functions
#
source $DOTFILES/shell/functions
# -----------------------------------------------------------------------------
# Setup completions
#
source $DOTFILES/zsh/completion
# -----------------------------------------------------------------------------
# History settings
#
export HISTSIZE=10000
export SAVEHIST=10000
setopt INC_APPEND_HISTORY   # replaces PROMPT_COMMAND='history -a'
setopt HIST_VERIFY           # replaces histverify
setopt HIST_IGNORE_ALL_DUPS  # replaces HISTCONTROL=ignoreboth
setopt HIST_IGNORE_SPACE     # replaces HISTCONTROL=ignorespace
# -----------------------------------------------------------------------------
# Shell options
#
setopt GLOB_DOTS     # replaces dotglob
setopt CDABLEVARS    # replaces cdable_vars
setopt EXTENDED_GLOB # replaces extglob
setopt NOTIFY        # replaces set -o notify
# -----------------------------------------------------------------------------
# Using VIM for editing
#
export EDITOR="vim"
# -----------------------------------------------------------------------------
# Make GPG play nice
#
export GPG_TTY=$(tty)
# -----------------------------------------------------------------------------
# Setup project stuff
#
export PROJECT_DIR="Projects"
# -----------------------------------------------------------------------------
# colored GCC warnings and errors
#
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# -----------------------------------------------------------------------------
# make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
# -----------------------------------------------------------------------------
# Better colors for less
#
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
# -----------------------------------------------------------------------------
# setup nvm
#
export NVM_DIR="$HOME/.nvm"
if _is_macos && command -v brew >/dev/null 2>&1; then
  [ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)/nvm.sh"
elif [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
fi
# -----------------------------------------------------------------------------
# setup pyenv
#
if command -v pyenv >/dev/null 2>&1; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi
# -----------------------------------------------------------------------------
# RVM completion
#
[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion
# -----------------------------------------------------------------------------
# Setup any machine-specific configs
#
[[ -s "$HOME/.zshrc.local" ]] && . "$HOME/.zshrc.local"
# -----------------------------------------------------------------------------
eval "$(starship init zsh)"
# -----------------------------------------------------------------------------
[ -s "$NVM_DIR/zsh_completion" ] && \. "$NVM_DIR/zsh_completion"
# -----------------------------------------------------------------------------
. "$HOME/.posthog/env"
# -----------------------------------------------------------------------------
# Enable shell command completion for gcloud.
#
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then
  . "$HOME/google-cloud-sdk/completion.zsh.inc"
fi
