#!/bin/bash
#
# https://github.com/misham/dotfiles
#
# Based on my fat-fingering and stuff I found on dotfiles.org
# and github.com
#
# -----------------------------------------------------------------------------
# Searches for a string in a directory and it's subdirectories
#
alias rgrep='find . -type f -print0 | xargs -0 grep --color=auto -i -n'
# -----------------------------------------------------------------------------
# use colordiff if it's available
#
if [[ -f /usr/bin/colordiff ]]; then
    alias diff='colordiff -u'
fi
# -----------------------------------------------------------------------------
# Setup ping for only 5 pings
#
alias ping='ping -c 5'
# -----------------------------------------------------------------------------
# Create directories as needed
#
alias mkdir='mkdir -p -v'
# -----------------------------------------------------------------------------
# Use color for grep
#
alias grep="grep --color=auto -n"
# -----------------------------------------------------------------------------
# Alias reconf to run autoreconf -i and configure scripts for me
#
alias reconf="autoreconf -i && ./configure"
# -----------------------------------------------------------------------------
# Go back to last directory
#
alias back='cd $OLDPWD'
# -----------------------------------------------------------------------------
# Some size information shortcuts
#
alias df='df -h'
alias du='du -h -c'
# -----------------------------------------------------------------------------
# Nice to know what your copying and moving
#
alias cp='cp -v'
alias mv='mv -v'
# -----------------------------------------------------------------------------
# Use nice delete
#
alias rm='rm -i'
# -----------------------------------------------------------------------------
# Sometimes lazy is good
#
alias ..='cd ..'

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -lF --color=auto'
alias la='ls -a --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

