#!/bin/bash
#
# https://github.com/misham/dotfiles
#
# Based on my fat-fingering and stuff I found on dotfiles.org
# and github.com
#
# -----------------------------------------------------------------------------
# use colordiff if it's available
#
if [[ -f "$(brew --prefix)/bin/colordiff" ]]; then
    alias diff='colordiff -u'
fi
# -----------------------------------------------------------------------------
# Setup ping for only 5 pings
#
alias ping='ping -c 5'
# -----------------------------------------------------------------------------
# Create directories as needed
#
alias mkdir='mkdir -p -v'
# -----------------------------------------------------------------------------
# Use color for grep
#
alias grep="grep --color=auto -n"
# -----------------------------------------------------------------------------
# Go back to last directory
#
alias back='cd $OLDPWD'
# -----------------------------------------------------------------------------
# Some size information shortcuts
#
alias df='df -h'
alias du='du -h -c'
# -----------------------------------------------------------------------------
# Nice to know what your copying and moving
#
alias cp='cp -v'
alias mv='mv -v'
# -----------------------------------------------------------------------------
# Use nice delete
#
alias rm='rm -i'
# -----------------------------------------------------------------------------
# Sometimes lazy is good
#
alias ..='cd ..'

# some more ls aliases
alias ls='ls -G'
alias ll='ls -GlhF'
alias la='ls -Ga'

