#
# My bash_profile - https://github.com/misham/dotfiles
#
# This is based on stock Ubuntu .profile
#

# if running bash
if [ -n "$BASH_VERSION" ]; then
    #
    # Check for custom dotfiles, otherwise, use the one in home dir
    #
    if [ -f "$HOME/.dotfiles/bash/bashrc" ]; then
        . "$HOME/.dotfiles/bash/bashrc"
    elif [ -f "$HOME/.bashrc" ]; then
	    . "$HOME/.bashrc"
    fi
fi

tmp_path="/sbin:/usr/sbin"
if [ -d "$HOME/bin" ] ; then
    tmp_path="$tmp_path:$HOME/bin"
fi
PATH="$PATH:$tmp_path"


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
