#
# https://github.com/misham/dotfiles
#
# This is based on stock Ubuntu .bashrc and stuff I found on dotfiles.org
# and github.com
#
DOTFILES=$HOME/.dotfiles
# -----------------------------------------------------------------------------
# OS Detection
#
_is_macos() { [[ "$(uname -s)" == "Darwin" ]]; }
_is_linux() { [[ "$(uname -s)" == "Linux" ]]; }
# -----------------------------------------------------------------------------
# macOS: Silence bash deprecation warning
if _is_macos; then
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi
# -----------------------------------------------------------------------------
# Get aliases
#
source $DOTFILES/bash/aliases
# -----------------------------------------------------------------------------
# Setup completion
#
source $DOTFILES/bash/completion
# -----------------------------------------------------------------------------
# Homebrew bash completion (macOS)
if _is_macos && command -v brew >/dev/null 2>&1; then
  export BASH_COMPLETION_COMPAT_DIR="$(brew --prefix)/etc/bash_completion.d"
  [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
fi
# -----------------------------------------------------------------------------
# Get functions
#
source $DOTFILES/bash/functions
# -----------------------------------------------------------------------------
# Set vi as my security blanket with some options
#
set -o vi
set editing-mode vi # I like all readline programs to use vi mode
set keymap vi
set convert-meta on
bind -m vi-insert "\C-l":clear-screen # Ctrl-l is still nice though
# -----------------------------------------------------------------------------
# Using VIM for editing
#
export EDITOR="vim"
# -----------------------------------------------------------------------------
# notify of bg job completion immediately
#
set -o notify
# -----------------------------------------------------------------------------
# Some housekeeping for history
#
export HISTSIZE=10000
export HISTFILESIZE=10000
PROMPT_COMMAND='history -a'
export HISTCONTROL=ignoredboth
shopt -s histappend histreedit histverify
# -----------------------------------------------------------------------------
# Set some options for bash
#
shopt -s cdspell
shopt -s dotglob
shopt -s checkwinsize
shopt -s cdable_vars
shopt -s checkhash
shopt -s cmdhist
shopt -s extglob
shopt -s hostcomplete
shopt -s no_empty_cmd_completion
# -----------------------------------------------------------------------------
# make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
# -----------------------------------------------------------------------------
# Better colors for less
#
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
# -----------------------------------------------------------------------------
# Make GPG play nice
#
export GPG_TTY=$(tty)
# -----------------------------------------------------------------------------
# Setup project stuff
#
export PROJECT_DIR="Projects"
# -----------------------------------------------------------------------------
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# -----------------------------------------------------------------------------
# setup nvm
export NVM_DIR="$HOME/.nvm"
if _is_macos && command -v brew >/dev/null 2>&1; then
  [ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)/nvm.sh"
elif [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
fi
# -----------------------------------------------------------------------------
# RVM completion
[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion
# -----------------------------------------------------------------------------
# Setup any machine-specific configs
[[ -s "$HOME/.bashrc.local" ]] && . "$HOME/.bashrc.local"
# -----------------------------------------------------------------------------
eval "$(starship init bash)"
# -----------------------------------------------------------------------------
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# -----------------------------------------------------------------------------
. "$HOME/.posthog/env"
# -----------------------------------------------------------------------------
# Enable shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then
  . "$HOME/google-cloud-sdk/completion.bash.inc"
fi

