#
# https://github.com/misham/dotfiles
#
# This is based on stock Ubuntu .bashrc and stuff I found on dotfiles.org
# and github.com
#
DOTFILES=$HOME/.dotfiles
#-----------------------------------------------------------------------------
# Make sure we're running interactively
if [[ -n "$PS1" ]]; then

#TODO make this mac-specific
export BASH_SILENCE_DEPRECATION_WARNING=1

# -----------------------------------------------------------------------------
# Get aliases
#
source $DOTFILES/bash/aliases
# -----------------------------------------------------------------------------
# Setup completion
#
source $DOTFILES/bash/completion
#
source $(brew --prefix)/etc/bash_completion
# -----------------------------------------------------------------------------
# Get functions
#
source $DOTFILES/bash/functions
# -----------------------------------------------------------------------------
# Set vi as my security blanket with some options
#
set -o vi
set editing-mode vi # I like all readline programs to use vi mode
set keymap vi
set convert-meta on
bind -m vi-insert "\C-l":clear-screen # Ctrl-l is still nice though
# -----------------------------------------------------------------------------
# Using VIM for editing
#
export EDITOR="vim"
# -----------------------------------------------------------------------------
# notify of bg job completion immediately
#
set -o notify
# -----------------------------------------------------------------------------
# Some housekeeping for history
#
export HISTSIZE=10000
export HISTFILESIZE=10000
PROMPT_COMMAND='history -a'
export HISTCONTROL=ignoredboth
shopt -s histappend histreedit histverify
# -----------------------------------------------------------------------------
# Set some options for bash
#
shopt -s cdspell
shopt -s dotglob
shopt -s checkwinsize
shopt -s cdable_vars
shopt -s checkhash
shopt -s cmdhist
shopt -s extglob
shopt -s hostcomplete
shopt -s no_empty_cmd_completion
# -----------------------------------------------------------------------------
# make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
# -----------------------------------------------------------------------------
# Better colors for less
#
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
# -----------------------------------------------------------------------------
# Setup project stuff
#
export PROJECT_DIR="Projects"
# -----------------------------------------------------------------------------
# Set Prompt
#
BLUE='\[\033[1;34m\]'
RED='\[\033[1;31m\]'
NORMAL='\[\033[00m\]'
NORMAL_BOLD='\[\033[00;01m\]'

CUR_PWD="${BLUE}[${RED}\w${BLUE}]"
CUR_TIME="${BLUE}[${NORMAL}\t${BLUE}]"
CUR_USER_HOST="${BLUE}[${NORMAL}\u${NORMAL_BOLD}@${NORMAL}\h${BLUE}]"

# NOTE using starship instead
#export PS1="${CUR_PWD} ${BLUE}[${NORMAL}\$(git_prompt)\$(svn_prompt)${BLUE}]\n${CUR_TIME} ${BLUE}[${NORMAL}\$(rvm_prompt)${BLUE}]\n${CUR_USER_HOST} ${NORMAL}$ "

# -----------------------------------------------------------------------------
# RVM completion
#
[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion

# -----------------------------------------------------------------------------
# NVM completion
#
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# -----------------------------------------------------------------------------
# Get colors
#
# TODO make this Linux specific
#test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#eval `dircolors $HOME/.dir_colors/dircolors`

fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/misham/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/misham/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/misham/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/misham/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

eval "$(starship init bash)"

