#
# https://github.com/misham/dotfiles
#
# This is based on stock Ubuntu .bashrc and stuff I found on dotfiles.org
# and github.com
#
DOTFILES=$HOME/.dotfiles
#-----------------------------------------------------------------------------
# Make sure we're running interactively
if [[ -n "$PS1" ]]; then
# -----------------------------------------------------------------------------
# Get colors
#
source "`brew --prefix grc`/etc/grc.bashrc"
export CLICOLOR=1
export LSCOLORS=exfxcxdxbxegedabagacad
# -----------------------------------------------------------------------------
# Get aliases
#
source $DOTFILES/bash/aliases
# -----------------------------------------------------------------------------
# Get functions
#
source $DOTFILES/bash/functions
# -----------------------------------------------------------------------------
# Setup completion
#
source $DOTFILES/bash/completion
# -----------------------------------------------------------------------------
# Set vi as my security blanket with some options
#
set -o vi
set editing-mode vi # I like all readline programs to use vi mode
set keymap vi
set convert-meta on
bind -m vi-insert "\C-l":clear-screen # Ctrl-l is still nice though
# -----------------------------------------------------------------------------
# Using VIM for editing
#
export EDITOR="vim"
# -----------------------------------------------------------------------------
# notify of bg job completion immediately
#
set -o notify
# -----------------------------------------------------------------------------
# Some housekeeping for history
#
export HISTSIZE=10000
export HISTFILESIZE=10000
PROMPT_COMMAND='history -a'
export HISTCONTROL=ignoredboth
shopt -s histappend histreedit histverify
# -----------------------------------------------------------------------------
# Set some options for bash
#
shopt -s cdspell
shopt -s dotglob
shopt -s checkwinsize
shopt -s cdable_vars
shopt -s checkhash
shopt -s cmdhist
shopt -s extglob
shopt -s hostcomplete
shopt -s no_empty_cmd_completion
# -----------------------------------------------------------------------------
# make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
# -----------------------------------------------------------------------------
# Better colors for less
#
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
# -----------------------------------------------------------------------------
# Setup project stuff
#
export PROJECT_DIR="Projects"
# -----------------------------------------------------------------------------
# Setup bash completion
#
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi
# -----------------------------------------------------------------------------
# Set Prompt
#
BLUE='\[\033[1;34m\]'
RED='\[\033[1;31m\]'
NORMAL='\[\033[00m\]'
NORMAL_BOLD='\[\033[00;01m\]'

CUR_PWD="${BLUE}[${RED}\w${BLUE}]"
CUR_TIME="${BLUE}[${NORMAL}\t${BLUE}]"
CUR_USER_HOST="${BLUE}[${NORMAL}\u${NORMAL_BOLD}@${NORMAL}\h${BLUE}]"

export PS1="${CUR_PWD} ${BLUE}[${NORMAL}\$(git_prompt)\$(svn_prompt)${BLUE}]\n${CUR_TIME} ${BLUE}[${NORMAL}\$(rvm_prompt)${BLUE}]\n${CUR_USER_HOST} ${NORMAL}$ "
# -----------------------------------------------------------------------------
# Get local modifications for bash, if they exist
#
if [[ -e $HOME/.bashrc.local ]]; then
  source $HOME/.bashrc.local
fi
# -----------------------------------------------------------------------------
# RVM completion
#
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion
# -----------------------------------------------------------------------------
# Homebrew options
#
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
# -----------------------------------------------------------------------------
# Setup NVM
#
export NVM_DIR="/Users/misham/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# -----------------------------------------------------------------------------
fi

