#
# My bash_profile - https://github.com/misham/dotfiles
#
# This is based on stock Ubuntu .profile
#

# if running bash
if [ -n "$BASH_VERSION" ]; then
  #
  # Check for custom dotfiles, otherwise, use the one in home dir
  #
  if [ -f "$HOME/.dotfiles/bash/bashrc" ]; then
    . "$HOME/.dotfiles/bash/bashrc"
  elif [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

tmp_path="/sbin:/usr/sbin"
if [ -d "/usr/local/bin" ] ; then
  tmp_path="/usr/local/bin:$tmp_path"
fi
if [ -d "/usr/local/sbin" ] ; then
  tmp_path="/usr/local/sbin:$tmp_path"
fi
if [ -d "$HOME/bin" ] ; then
  tmp_path="$HOME/bin:$tmp_path"
fi

PATH="$tmp_path:$PATH"


### Added by the Heroku Toolbelt
PATH="/usr/local/heroku/bin:$PATH"

# Add CodeSourcery Light path
PATH="/Users/misham/gcc-arm-none-eabi-4_7-2013q3/bin:$PATH"

# Add CoreUtils for Mac
#PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
#MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export PATH="$PATH"

export MATHPATH="$MANPATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

