#
# My bash_profile - https://github.com/misham/dotfiles
#
# This is based on stock Ubuntu .profile
#

# if running bash
if [ -n "$BASH_VERSION" ]; then
  #
  # Check for custom dotfiles, otherwise, use the one in home dir
  #
  if [ -f "$HOME/.dotfiles/bash/bashrc" ]; then
    . "$HOME/.dotfiles/bash/bashrc"
  elif [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

tmp_path="/sbin:/usr/sbin"
if [ -d "/usr/local/bin" ] ; then
  tmp_path="/usr/local/bin:$tmp_path"
fi
if [ -d "/usr/local/sbin" ] ; then
  tmp_path="/usr/local/sbin:$tmp_path"
fi

tmp_path="$tmp_path:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin"
tmp_path="$tmp_path:/snap/bin"

if [ -d "$HOME/bin" ] ; then
  tmp_path="$HOME/bin:$tmp_path"
fi

tmp_path="$tmp_path:/usr/local/heroku/bin"

tmp_path="$tmp_path:/opt/android-studio/bin"
tmp_path="$tmp_path:$HOME/Android/Sdk/tools"
tmp_path="$tmp_path:$HOME/Android/Sdk/tools/bin"
tmp_path="$tmp_path:$HOME/Android/Sdk/platform-tools"
tmp_path="$tmp_path:/opt/android-studio/gradle/gradle-4.1/bin"
tmp_path="$tmp_path:$HOME/.local/bin"

PATH="$tmp_path:$PATH"

export MATHPATH="$MANPATH"

export ANDROID_HOME="$HOME/Android/Sdk"


# ----- LAST LINE -----

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

