#!/bin/bash
#
# https://github.com/misham/dotfiles
#
# Based on stuff I found on dotfiles.org and github.com
#
# -----------------------------------------------------------------------------
# Calculator function
#
# @param $* What to calculate
#
calc()
{
  echo "$*" | bc -l ;
} # calc

# -----------------------------------------------------------------------------
# Uncompress a passed in file
#
# @param $1 File to uncompress
#
extract ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)
        tar -xjvpf $1
        ;;
      *.tar.gz)
        tar -xzvpf $1
        ;;
      *.bz2)
        bunzip2 $1
        ;;
      *.rar)
        rar x $1
        ;;
      *.gz)
        gunzip $1
        ;;
      *.tar)
        tar -xvpf $1
        ;;
      *.tbz2)
        tar -xjvpf $1
        ;;
      *.tgz)
        tar xzf $1
        ;;
      *.zip)
        unzip $1
        ;;
      *.Z)
        uncompress $1
        ;;
      *)
        echo "'$1' cannot be extracted via extract()"
        ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
} # extract

# -----------------------------------------------------------------------------
# Grep for the specified process
#
# @param $1 Process to grep for
#
psgrep()
{
  if [ ! -z $1 ] ; then
    echo "Grepping for processes matching $1..."
    ps aux | grep $1 | grep -v grep
  else
    echo "!! Need name to grep for"
  fi
} # psgrep

# -----------------------------------------------------------------------------
# Push SSH public key to another box
#   from https://github.com/rtomayko/dotfiles
#
push_ssh_cert() {
    local _host
    test -f ~/.ssh/id_rsa.pub || ssh-keygen -t rsa
    for _host in "$@";
    do
        echo $_host
        ssh $_host 'cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_dsa.pub
    done
}

